ALTER TABLE dues ADD COLUMN IF NOT EXISTS period_start DATE;
ALTER TABLE dues ADD COLUMN IF NOT EXISTS period_end DATE;
ALTER TABLE dues ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE dues ADD COLUMN IF NOT EXISTS demirbas_amount NUMERIC(12,2) DEFAULT 0;
ALTER TABLE dues ADD COLUMN IF NOT EXISTS normal_amount NUMERIC(12,2) DEFAULT 0;
ALTER TABLE dues DROP COLUMN IF EXISTS due_type;
