ALTER TABLE sites ADD COLUMN IF NOT EXISTS gecikme_turu VARCHAR(10) DEFAULT 'gunluk';
ALTER TABLE sites ADD COLUMN IF NOT EXISTS gecikme_oran NUMERIC(5,2) DEFAULT 0;
ALTER TABLE dues  ADD COLUMN IF NOT EXISTS gecikme_gun INTEGER DEFAULT 0;
ALTER TABLE dues  ADD COLUMN IF NOT EXISTS gecikme_bedel NUMERIC(12,2) DEFAULT 0;
