ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_pw BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_exp TIMESTAMP;
